[package]
name = "rustracer"
version = "0.1.0"
authors = ["Mikastiv <m.leblanc_3@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = ""
image = ""
num_cpus = ""
indicatif = ""
serde = { version = "", features = ["derive"] }
serde_json = ""